[package]
name = "aura-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }